
sudo: false
dist: trusty
language: node_js
node_js:
- '8'
before_install:
- if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
install:
- npm install
before_script:
- npm install -g bower
- bower install
script:
- eslint src
notifications:
  email: false
addons:
  sauce_connect: true
env:
  global:
  - secure: WaVOK6cJFnrE0iOus1sV3JnDFvIdvi6AohhKgcH9KZyz6KALGsKr7az8RRlNtdtu45yxva7eJV4dHyaS7C7R0fd4kUPWwwKjnqLQ78caQwPfh6/KZ1EWkEUFEqL4pYq6Tw59Cw8e1/uXOkqc6qVQRXIFNeiV+7hEWPeY+48YmPOu5V7PXhVJgStLKq5iniifwIXdnjGkTzb6zbvQt0i5/wf4zv1Ih0Ur7cRWX0qUax7cP4j8MBfWtKUQ8VktJKpk1zvDqLsynFWwFbJ6LyPTH5Ko6JIDYR51soY0Lsox+0rcX3sikMatbrVaT19x5xc9dlB5EJyrbo5YeiliPlQWBUxpolM4lVaurukTXQijIf1S6Nzsz9s+HJrfKwUuQfhewGK3h6ps7/HJIHB6RjfdUa9P/0PXtVvnBV14hxHoojB92Vlfb1QddgzbDXLv/Vl7jyKiQXkrOX6UFPQ6VJyYYuIKHuJ4MzxaVqTtrXxOBJ71uIN7CnLMhsQjpDFFTUiRqeUSvdMQYux7aVz3TtR4vWWKNtsukcOeJLaiAqxUmHX1Mejll0ZRyRkPhzzOPiX+wgBwPvZ3H+JYfYT5DvH/GAMe0FfyqQhYtM27wSEG9das0Q4m40G054A0ztKmxJn1D+NC6NuCfgfqHyo/5M+7kWu1Vt6cnYTIj3ZII2rZPaA=
  - secure: m8WtkyXZk8SyNAU4NxKp/W6VfkcM0GJCF9dJTeeXd4CBjUkVMtvZcsjC3lxwWkogU75woDXBgBY6dq/mU45esAReQ3g8YoX66g2cfOAbGGQW6iNXyUN+xE9bR+ntZrgq/CTmQ4hpGSmboF0hS9/QCN9R4eGJHEJS6ju/CHIMiSfMe/kNR0rDuFsELJkXKAX+bGtauizITuEuMBK1aoV4Xnva77gyZtuWkJjRvat+Suy9UqGxVRnEyyM/LjgLZS9kM6DPJ2iMc/Dan1z8O3oaVn/aodGh9YVl2rZvKXmchWeyRyCmkDpj1dPioC1yvgFgAZPBFeDEJvITIQ8C3Gpj6OqYyZpRsuF7zag+fdHSMGCtTVmJHICkf0k1MLU0AK1fJ+ABFf4JbRyChYLct03D9VPEOc/oRluQf4Q/DJmEcwrCrFxRExbBMcGMq7bjcaP0XRwG2/CPBQ/k5ic+IwlB/TicJWg3xeCYbVYEDmcjHxqDObVu1/Fbt3k3zamPfzsN3zOtqyi4zj5lSVomxp/wOs/8xA3EFD07UfpRB2UhnOlYgEf1H5UgZc6arR9IAj4XNG4VRaMlwTk0VcxDg6iBq2kybyw69uP2FjlcfXFLINFwlojLn2IoIMfOsBUQYkBHKpZbg3ro6SpzrCBfhqnGH+3ONjKFVxEmmH4YOi+HmkU=
